---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-02eb4d94563df7380
      gp3: ami-0a7d702573704c565
    ap-east-1:
      io2: ami-0407a0c566867bd6a
      gp3: ami-08cb814e4c378d58e
    ap-northeast-1:
      io2: ami-016bd6c921eb4337e
      gp3: ami-08b26dce504c5ecd7
    ap-northeast-2:
      io2: ami-08de2cca67f2be087
      gp3: ami-08c86387631a0d975
    ap-south-1:
      io2: ami-0d3956759e3a0784f
      gp3: ami-00cdc76c590cdd8cf
    ap-southeast-1:
      io2: ami-093fd9b3e39611860
      gp3: ami-0df9ece6f42f01b27
    ap-southeast-2:
      io2: ami-03f80700214da6b9e
      gp3: ami-0bd8b0faed7334303
    ap-southeast-3:
      io2: ami-0332469f12942d611
      gp3: ami-0363b75f8bce33987
    ca-central-1:
      io2: ami-0fd878681265974dd
      gp3: ami-047fcf00ef6f774a5
    eu-central-1:
      io2: ami-073d95af398167c4f
      gp3: ami-0f6337ecb70e2ce20
    eu-north-1:
      io2: ami-003a8274d47fab79d
      gp3: ami-08e2dbef851243881
    eu-south-1:
      io2: ami-07f752b8635919513
      gp3: ami-0205d326fee61af31
    eu-west-1:
      io2: ami-058034b37856da3a7
      gp3: ami-0ad2ddfe55064c693
    eu-west-2:
      io2: ami-01be38ffa4b7043db
      gp3: ami-0bc463d738040c4d6
    eu-west-3:
      io2: ami-0ca2a4f7c0fb52838
      gp3: ami-02df9724ea4edbf0a
    me-central-1:
      io2: ami-0acbe9faa90fb5a94
      gp3: ami-0ccc91becfb892d47
    me-south-1:
      io2: ami-0f41d1887a58e2b0a
      gp3: ami-0397d146464ee9192
    sa-east-1:
      io2: ami-0b8509319c8dd573f
      gp3: ami-07440fe37d287760a
    us-east-1:
      io2: ami-020de6e9688c2a28e
      gp3: ami-0c6b3f6d254a02704
    us-east-2:
      io2: ami-04acec50ecce31209
      gp3: ami-0de86e3366ba55840
    us-west-1:
      io2: ami-0b7eef68a1e557c4f
      gp3: ami-0043ad121ed288c20
    us-west-2:
      io2: ami-0f8216667d87200a3
      gp3: ami-03d6fef3fb356ff72

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
