---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-037cfcd06852a2ade
      gp3: ami-0113dff1f2658ef5b
    ap-east-1:
      io2: ami-014b64ac3a71b6d60
      gp3: ami-02da94db868c082ea
    ap-northeast-1:
      io2: ami-012d2f74ad2145434
      gp3: ami-0c34aa0e579420d5a
    ap-northeast-2:
      io2: ami-0b8487a46c7dc4067
      gp3: ami-093dae2f00143ac4d
    ap-south-1:
      io2: ami-0bd36592287db76f3
      gp3: ami-016befcc760ed2a00
    ap-southeast-1:
      io2: ami-0bbaac9274d4c57f0
      gp3: ami-0b01896be44153dbe
    ap-southeast-2:
      io2: ami-090db52b6d6519ebe
      gp3: ami-0c39854a221f44031
    ap-southeast-3:
      io2: ami-0e57134d0cb2f46f4
      gp3: ami-04dcca3c1ad54a50b
    ca-central-1:
      io2: ami-0d6f839b3abd5b2a4
      gp3: ami-09e78d6e528b80040
    eu-central-1:
      io2: ami-00f54465108abb35d
      gp3: ami-02a2cc61c02ff782a
    eu-north-1:
      io2: ami-0e11678c7386cdf67
      gp3: ami-01b73ce0635eaf51f
    eu-south-1:
      io2: ami-06166210b50fb9bac
      gp3: ami-0f2730ec98ea7255d
    eu-west-1:
      io2: ami-00cb8420bd77826b2
      gp3: ami-02b08bd95721455fa
    eu-west-2:
      io2: ami-07d0d997ee74c8f5a
      gp3: ami-0bd3b77a9aceaaac0
    eu-west-3:
      io2: ami-009f0dd5f1e4907e5
      gp3: ami-0deb6bd3f81fbde8f
    me-central-1:
      io2: ami-0244f87730a9775d6
      gp3: ami-057516eae2d2a0293
    me-south-1:
      io2: ami-0dcf60ecb4fe54624
      gp3: ami-0e4fb67cceb7fb366
    sa-east-1:
      io2: ami-02635d6d4644d1d99
      gp3: ami-06820d6812668eaeb
    us-east-1:
      io2: ami-0d36723d7a26e388a
      gp3: ami-071e2b636c6949fa9
    us-east-2:
      io2: ami-0902f5471c8bc130c
      gp3: ami-0d7e54af4c3627be0
    us-west-1:
      io2: ami-0d5ff664aca6c765a
      gp3: ami-0b918a7fc6ee0544b
    us-west-2:
      io2: ami-0f3a28c16f8de0698
      gp3: ami-0081d04a5bde4c304

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
