---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-0a43d892db830f18c
      gp3: ami-0b888c7dad09a532c
    ap-east-1:
      io2: ami-0205b74d99e00e2df
      gp3: ami-0f7ff9d3f4bb59004
    ap-northeast-1:
      io2: ami-08168ff937bd6422e
      gp3: ami-0d1eace60e3a00766
    ap-northeast-2:
      io2: ami-0200f79ee4ddba74e
      gp3: ami-057ee905c72032044
    ap-south-1:
      io2: ami-0e6bf070fa3337275
      gp3: ami-0b11b1f78bac5dbc3
    ap-southeast-1:
      io2: ami-09d3c7677182053c3
      gp3: ami-0b2f17b3516e70a6e
    ap-southeast-2:
      io2: ami-0b14afa611866fa13
      gp3: ami-0e45272b66a7e7dab
    ap-southeast-3:
      io2: ami-078f8932d605d62fe
      gp3: ami-0c7fb17d16d3bae17
    ca-central-1:
      io2: ami-05e2bb10f19b9bc79
      gp3: ami-0995aeed241756e92
    eu-central-1:
      io2: ami-0bd4db6701ec5e555
      gp3: ami-0dd1a4abe5b6f1f6c
    eu-north-1:
      io2: ami-0ecd091dc2192cab8
      gp3: ami-0a2f45149c6949768
    eu-south-1:
      io2: ami-039cf41b2e12d2773
      gp3: ami-07651c5d667125e57
    eu-west-1:
      io2: ami-01c372fb82567030a
      gp3: ami-03c14285126c1a8dd
    eu-west-2:
      io2: ami-0b2c3e18c7655d7f5
      gp3: ami-071e8956237151e45
    eu-west-3:
      io2: ami-008c3038ff49d74a1
      gp3: ami-0b4e8bff14efc4f37
    me-central-1:
      io2: ami-0d103e074996a5d91
      gp3: ami-0592236d7de0e182a
    me-south-1:
      io2: ami-0627b728abf5da3ef
      gp3: ami-0e116feb73d9677d0
    sa-east-1:
      io2: ami-0cb3dbe6336d46bdb
      gp3: ami-0b48b94ee38c8115e
    us-east-1:
      io2: ami-013e7532c50922821
      gp3: ami-0623ee3651eebb7bb
    us-east-2:
      io2: ami-0b92cb0866c04cc8e
      gp3: ami-0725e08a155119b9d
    us-west-1:
      io2: ami-08b8429d521c473b0
      gp3: ami-07da60ffe72ba0303
    us-west-2:
      io2: ami-0ac15f0e6c9d5b8b7
      gp3: ami-0d5c454a7f85154fe

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
