---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-0706e23ef023e90d6
      gp3: ami-05d4ad19563598be2
    ap-east-1:
      io2: ami-02b8e6291e4bd1bc5
      gp3: ami-0f43173df12e371a9
    ap-northeast-1:
      io2: ami-0ceb8cf8c5f2c70bd
      gp3: ami-024c57a68a740c5de
    ap-northeast-2:
      io2: ami-0c875c4fbe4dfc274
      gp3: ami-00a5ecfd7e0832e97
    ap-south-1:
      io2: ami-0ca0e7ba6a61f23cd
      gp3: ami-00b19b4993b428c83
    ap-southeast-1:
      io2: ami-0487c471f359713ff
      gp3: ami-0a049f41febed922c
    ap-southeast-2:
      io2: ami-0d61223de71060980
      gp3: ami-07797a71074d1b219
    ap-southeast-3:
      io2: ami-002c2a4235aa91efa
      gp3: ami-0c45334dfb002c32e
    ca-central-1:
      io2: ami-04e2b9b085db2bba5
      gp3: ami-0660f7934c062f0c4
    eu-central-1:
      io2: ami-08879b84b8553da7f
      gp3: ami-07d4db0f650e6fbbc
    eu-north-1:
      io2: ami-0ea8a968189760a19
      gp3: ami-0fbba268a20cee9a2
    eu-south-1:
      io2: ami-0e22f5c1cfeb141a7
      gp3: ami-0e5b0363e03e29736
    eu-west-1:
      io2: ami-0af9a96d8e85f7731
      gp3: ami-0d24b9cc89bafe37e
    eu-west-2:
      io2: ami-096a65c601af63e5e
      gp3: ami-0b43f529c7c378e10
    eu-west-3:
      io2: ami-0f389eec522557a8c
      gp3: ami-0809e1d7cbd3b1a9a
    me-central-1:
      io2: ami-0b19733df113235cd
      gp3: ami-00d222c0fa230ae7d
    me-south-1:
      io2: ami-00d573b86843b1895
      gp3: ami-07c0c03852f12053a
    sa-east-1:
      io2: ami-0ee98ae59ee180c7c
      gp3: ami-0858af29073a66f96
    us-east-1:
      io2: ami-0c3a18459a9f54dbd
      gp3: ami-0e9e6f62345670c1f
    us-east-2:
      io2: ami-0e14180c11ff1ba68
      gp3: ami-0e42235df3669b354
    us-west-1:
      io2: ami-03e9198f6dcc63feb
      gp3: ami-00d5d863ff5dc380a
    us-west-2:
      io2: ami-0062d0f397b7fcd79
      gp3: ami-0b6a4b6bbc1fb707d

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
