---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  SourcegraphKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: SSH key pair to access the EC2 instance running Sourcegraph
  SourcegraphSize:
    Type: String
    Description: See docs for more info docs.sourcegraph.com/admin/deploy/machine-images/aws-oneclick
    Default: XS
    AllowedValues:
      - XS
      - S
      - M
      - L
      - XL

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups: 
      - 
        Label: 
          default: "EC2 Configuration"
        Parameters: 
          - SourcegraphKeyPair
      - 
        Label: 
          default: "Sourcegraph Configuration"
        Parameters: 
          - SourcegraphSize
    ParameterLabels:
      SourcegraphKeyPair:
        default: "SSH Keypair"
      SourcegraphSize:
        default: "Sourcegraph Instance Size"

Resources:
  SourcegraphSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables the ports Sourcegraph requires (22, 80, 443)
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 443
        ToPort: 443
        CidrIp: 0.0.0.0/0
  SourcegraphInstance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref SourcegraphKeyPair
      Tags:
      - Key: Name
        Value: Sourcegraph
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - Ref: AWS::Region
        - Fn::FindInMap:
          - SizeToType
          - Ref: SourcegraphSize
          - Type
      InstanceType: 
        Fn::FindInMap:
        - InstanceType
        - Ref: SourcegraphSize
        - Instance
      SecurityGroupIds:
        - !Ref SourcegraphSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          export SOURCEGRAPH_SIZE=${SourcegraphSize}
          bash /home/ec2-user/install.sh

Mappings:
  SizeToType:
    XS:
      Type: gp3
    S:
      Type: gp3
    M:
      Type: gp3
    L:
      Type: io2
    XL:
      Type: io2
  InstanceType:
    XS: 
      Instance: m6a.2xlarge
    S: 
      Instance: m6a.4xlarge
    M: 
      Instance: m6a.8xlarge
    L: 
      Instance: m6a.12xlarge
    XL: 
      Instance: m6a.24xlarge
  RegionMap:
    af-south-1:
      io2: ami-03b589860e4e202e3
      gp3: ami-0e5f452099ad39711
    ap-east-1:
      io2: ami-05bfc16c19107c3e5
      gp3: ami-03fc75249149db2fb
    ap-northeast-1:
      io2: ami-01dc48f0c8f025082
      gp3: ami-0cf6a1cbb809bebfd
    ap-northeast-2:
      io2: ami-0f3c6d66938e8004a
      gp3: ami-02436743a9282f03a
    ap-south-1:
      io2: ami-01b85d86db6d88243
      gp3: ami-06f8168e53d5a4e9e
    ap-southeast-1:
      io2: ami-03a1ace0b8831c84f
      gp3: ami-07444aa5e84399df4
    ap-southeast-2:
      io2: ami-0e97f95914a9fb52d
      gp3: ami-0aefd8327903b2aa6
    ap-southeast-3:
      io2: ami-025773145108fc82c
      gp3: ami-08993518bc71e4bb6
    ca-central-1:
      io2: ami-09bb1d86875a61058
      gp3: ami-0f9b16a49bbbeb80a
    eu-central-1:
      io2: ami-06a2faf7b9bf762c3
      gp3: ami-0729a4afbe606e700
    eu-north-1:
      io2: ami-0e5c035bf1a459cde
      gp3: ami-0a23b7ddb79a7d795
    eu-south-1:
      io2: ami-082bcabfc813b7f90
      gp3: ami-04660bc177a3e52db
    eu-west-1:
      io2: ami-05dc2274e055101a1
      gp3: ami-0fefda27252e21097
    eu-west-2:
      io2: ami-08d4f5bef5e5f8f39
      gp3: ami-05c88846f3e1d3213
    eu-west-3:
      io2: ami-02c51c68629e9c713
      gp3: ami-09869cab5ec23a1be
    me-central-1:
      io2: ami-0a414ce17484eb0b5
      gp3: ami-02ea486a0025dab2f
    me-south-1:
      io2: ami-049b9568388331d91
      gp3: ami-0eb224df4b288f0b6
    sa-east-1:
      io2: ami-029e12c4cc924ac7f
      gp3: ami-04a28999348567984
    us-east-1:
      io2: ami-06b6ef993569bbf76
      gp3: ami-09b2c32a2fcef0428
    us-east-2:
      io2: ami-00e951b80c085c060
      gp3: ami-063a5c531c8a94309
    us-west-1:
      io2: ami-0d2b62b1489105775
      gp3: ami-02814acd37a5e9b5a
    us-west-2:
      io2: ami-0a2f47ffaa432aa85
      gp3: ami-010b5768bd043b95d

Outputs:
  SourcegraphURL:
    Description: URL for your Sourcegraph instance - sign in here!
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - SourcegraphInstance
          - PublicIp
        - ":80"
