steps:
  - label: ":bazel: Build"
    agents:
      queue: bazel
    commands: |
      env | grep AWS
      export AWS_ACCESS_KEY_ID=$RELEASE_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=somethingishere
      bazel run //:packer -- init --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
      bazel run //:packer -- build -var "instance_version=$RELEASE_NUMBER" -var "dev=$DEV" --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
