steps:
  - label: ":bazel: Build"
    plugins:
      - thedyrt/git-commit#v0.3.0:
        add: CHANGELOG.md
        branch: bazel-changelog-test
        message: "Updated CHANGELOG.md"
        remote: upstream
        user:
          name: Anish
          email: anish.lakhwara@sourcegraph.com
    agents:
      queue: bazel
    commands: |
      export AWS_ACCESS_KEY_ID=$$RELEASE_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=$$RELEASE_AWS_SECRET_KEY
      bazel run //:packer -- init --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
      bazel run //:packer -- build -var "instance_version=$RELEASE_NUMBER" -var "dev=$DEV" --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
      bazel run //:generate-changelog
