name: packer

on: workflow_dispatch

jobs:
  packer:
    runs-on: ubuntu-latest
    name: build and publish AMIs
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`

      - env: 
          AWS_ACCESS_KEY_ID: {{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: {{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: us-west-1 

      - name: Run `packer init`
        run: "packer init --var-file=./packer/dev/dev-variables.hcl ./packer/dev/dev-builder.pkr.hcl"
      - name: Run `packer init`
        run: "packer init --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl"
      - name: Run `packer init`
        run: "packer init --var-file=./packer/build-variables.hcl ./packer/aws-latest/aws-builder.pkr.hcl"
      - name: Run `packer init`   
        run: "packer init --var-file=./packer/build-variables.hcl ./packer/gcp/gcp-builder.pkr.hcl"

      # Need step to pull in env vars for packer to AWS
      

